#!/usr/bin/env node
// ─────────────────────────────────────────────────────────────
// inline-worker — build-time worker source inliner
// ─────────────────────────────────────────────────────────────
//
// Reads the just-built worker bundle from `dist/worker/layout.worker.js`
// and writes its contents into `src/.generated/worker-inline.ts` as
// `export const WORKER_SOURCE = "...";`. The main bundle then statically
// imports this constant — making the worker self-contained and safe to
// instantiate as a Blob URL in any modern bundler (Next.js, Vite,
// Webpack 5, Remix, CRA, esbuild).
//
// Idempotent: writes only if the content changed (avoids spurious
// rebuilds in watch mode).

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');

const WORKER_PATH = join(repoRoot, 'dist', 'worker', 'layout.worker.js');
const GEN_DIR = join(repoRoot, 'src', '.generated');
const GEN_PATH = join(GEN_DIR, 'worker-inline.ts');

async function main() {
  if (!existsSync(WORKER_PATH)) {
    console.error(
      `[inline-worker] Worker bundle not found at ${WORKER_PATH}. ` +
        'Did the worker build step run before this?',
    );
    process.exit(1);
  }

  const source = await readFile(WORKER_PATH, 'utf8');
  // Use JSON.stringify to safely escape the string. The result is a valid
  // JS string literal, so `export const X = ${JSON.stringify(s)};` is correct.
  const contents =
    '// AUTO-GENERATED — do not edit. Regenerated by `scripts/inline-worker.mjs`.\n' +
    `// Source: dist/worker/layout.worker.js (${source.length} bytes)\n` +
    'export const WORKER_SOURCE: string = ' +
    JSON.stringify(source) +
    ';\n';

  if (!existsSync(GEN_DIR)) {
    await mkdir(GEN_DIR, { recursive: true });
  }

  let prev = '';
  if (existsSync(GEN_PATH)) {
    prev = await readFile(GEN_PATH, 'utf8');
  }

  if (prev === contents) {
    console.log('[inline-worker] No changes; skipping write.');
    return;
  }

  await writeFile(GEN_PATH, contents, 'utf8');
  const sizeKB = (source.length / 1024).toFixed(1);
  console.log(`[inline-worker] Wrote ${GEN_PATH} (${sizeKB} KB worker source).`);
}

main().catch((err) => {
  console.error('[inline-worker] Fatal:', err);
  process.exit(1);
});
